name: metadata
channels:
- conda-forge
dependencies:
- conda-forge::python=3.8.5
- conda-forge::pandas=1.1.3
- conda-forge::numpy=1.19.2
- conda-forge::pathlib=1.0.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.3.4
- conda-forge::tabulate=0.8.7
